version: '3.9'

services:

  rent_request_service:
    container_name: rent_request_service
    build:
      context: services/RentRequest
      dockerfile: Dockerfile
    volumes:
      - ./services/RentRequest/src:/app
    ports:
      - "4000:4000"
    networks:
      - app_network

  tg_bot:
    build:
      context: bot
      dockerfile: bot/src/Dockerfile
    container_name: telegram_BOT
    volumes:
      - ./bot:/app
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rent
      POSTGRES_PASSWORD: rent
      POSTGRES_DB: rentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

#  redis:
#    image: redis:alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - rentBotNetwork

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local