version: '3.9'

services:
  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/src/public:/var/www/html/public
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rentBotNetwork
    depends_on:
      - rent_api

  rent_api:
    build:
      context: services/php-fpm
      dockerfile: Dockerfile
    container_name: rentAPI
    ports:
      - "9000:9000"
    volumes:
      - ./rent-api:/var/www/html
      - ./services/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    networks:
      - rentBotNetwork

  tg_bot:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: telegram_BOT
    volumes:
      - ./bot:/app
    networks:
      - rentBotNetwork

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rent
      POSTGRES_PASSWORD: rent
      POSTGRES_DB: rentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rentBotNetwork

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - rentBotNetwork

networks:
  rentBotNetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local