version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - rent_request_service
      - subscribes_service

  rent_request_service:
    container_name: rent_request_service
    build:
      context: services/RentRequest
      dockerfile: Dockerfile
    expose:
      - "4000"
    volumes:
      - ./services/RentRequest/src:/app
    networks:
      - app_network

  subscribes_service:
    container_name: subscribes_service
    build:
      context: services/Subscribes
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./services/Subscribes/src:/app
    networks:
      - app_network

  tg_bot:
    build:
      context: bot
      dockerfile: Dockerfile
    container_name: telegram_BOT
    volumes:
      - ./bot:/app
    ports:
      - "3000:3000"
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local